### ISSUE TITLE
binaries not linked on install

### ISSUE THREAD

**Issue by zkat** [zkat/cipm#4]
cipm doesn't link binaries for deps yet, so lifecycle scripts that use them... can't.

**Comment by rmg** [comment]
Just as a general status update, this seems to be the main blocker for most of the CI jobs I manage.

Current workaround now that #7 landed is `cipm --ignore-scripts && npm rebuild`, which works fine as long as the root package itself doesn't have any scripts to execute during install (since they're skipped by `npm rebuild`).
